version: '3'
services:
  mysql:
    container_name: mysqlcontainer
    image: mysql/mysql-server:8.0.24-1.2.2-server
    environment:  
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_ROOT_HOST: "%"
    volumes:
        - ./dbdata:/var/lib/mysql
        - ./database:/docker-entrypoint-initdb.d
    networks:
        - pfa-app-db
    restart: always
  node:
    container_name: nodecontainer
    build:
        context: app 
    depends_on:
        - mysql    
    networks:
        - pfa-app-db
        - pfa-app-proxy
    entrypoint:  dockerize -wait tcp://mysql:3306 -timeout 30s
    command: "node index.js"
  nginx:
    container_name: nginxcontainer
    build:
        context: nginx 
    ports: 
        - 8000:80
    restart: on-failure
    entrypoint: dockerize -wait tcp://node:3000 -timeout 60s /docker-entrypoint.sh nginx -g 'daemon off;'
    depends_on:
        - node    
    networks:
        - pfa-app-proxy
networks:
    pfa-app-db:
        driver: bridge      
    pfa-app-proxy:
        driver: bridge      
